# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeacherGUIQtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1081, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 10, 1041, 711))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 10, 1011, 661))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 10, 1011, 661))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_5.setGeometry(QtCore.QRect(10, 10, 991, 611))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_5.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_5.addTab(self.tab_10, "")
        self.tabWidget_4.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton = QtWidgets.QPushButton(self.tab_8)
        self.pushButton.setGeometry(QtCore.QRect(370, 250, 281, 111))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget_4.addTab(self.tab_8, "")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_6.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 1011, 661))
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tabWidget_6.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit.setGeometry(QtCore.QRect(40, 40, 201, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 50, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 110, 201, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_3.setGeometry(QtCore.QRect(620, 120, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 210, 1021, 461))
        self.tableWidget_2.setRowCount(11)
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tabWidget_6.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_13)
        self.tabWidget_7.setGeometry(QtCore.QRect(20, 10, 1011, 661))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_7.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tabWidget_7.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.tabWidget_7.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.tabWidget_7.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.tabWidget_7.addTab(self.tab_18, "")
        self.tabWidget_6.addTab(self.tab_13, "")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(1)
        self.tabWidget_6.setCurrentIndex(1)
        self.tabWidget_7.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Essay"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Short Answer"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Manually Marking"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_9), _translate("MainWindow", "True Or False"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_10), _translate("MainWindow", "Four Options"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("MainWindow", "Multiple Choice"))
        self.pushButton.setText(_translate("MainWindow", "Generate Random Maths Question "))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("MainWindow", "Random Maths"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Automatically Marking"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Create Question"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_11), _translate("MainWindow", "The Bank"))
        self.pushButton_2.setText(_translate("MainWindow", "Search By Year Level"))
        self.pushButton_3.setText(_translate("MainWindow", "Search By Phrase"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_12), _translate("MainWindow", "Search The Bank By Tag"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_14), _translate("MainWindow", "Random Maths"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_15), _translate("MainWindow", "True or False"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_16), _translate("MainWindow", "Four Options"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_17), _translate("MainWindow", "Essay"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_18), _translate("MainWindow", "Short Answer"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_13), _translate("MainWindow", "View Or Modify Question"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Questions Bank"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

