# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeacherGUIQtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TeacherMainWindow(object):
    def setupUi(self, TeacherMainWindow):
        TeacherMainWindow.setObjectName("TeacherMainWindow")
        TeacherMainWindow.resize(1131, 857)
        self.centralwidget = QtWidgets.QWidget(TeacherMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1081, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_5.setGeometry(QtCore.QRect(10, 10, 1021, 661))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton = QtWidgets.QPushButton(self.tab_10)
        self.pushButton.setGeometry(QtCore.QRect(740, 380, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab_10)
        self.label_2.setGeometry(QtCore.QRect(460, 430, 141, 71))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(240, 240, 181, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_3 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_2.addWidget(self.textEdit_3)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 410, 181, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_3.addWidget(self.radioButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_4 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_3.addWidget(self.textEdit_4)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_4.setGeometry(QtCore.QRect(240, 410, 181, 131))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_5 = QtWidgets.QTextEdit(self.layoutWidget_4)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_4.addWidget(self.textEdit_5)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_5.setGeometry(QtCore.QRect(440, 240, 181, 131))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_5.addWidget(self.radioButton_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_6 = QtWidgets.QTextEdit(self.layoutWidget_5)
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_5.addWidget(self.textEdit_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_5.setGeometry(QtCore.QRect(670, 270, 281, 81))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.tab_10)
        self.label_4.setGeometry(QtCore.QRect(710, 470, 201, 51))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.layoutWidget_15 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_15.setGeometry(QtCore.QRect(30, 240, 181, 131))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget_15)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget_15)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.layoutWidget_16 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_16.setGeometry(QtCore.QRect(30, 20, 461, 181))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_16)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget_16)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget_16)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.layoutWidget_17 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_17.setGeometry(QtCore.QRect(620, 50, 271, 51))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_17)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_17)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_7.addWidget(self.lineEdit_3)
        self.layoutWidget_18 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_18.setGeometry(QtCore.QRect(620, 140, 271, 51))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_18)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_8.addWidget(self.lineEdit_4)
        self.tabWidget_5.addTab(self.tab_10, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(680, 300, 281, 81))
        self.pushButton_6.setObjectName("pushButton_6")
        self.layoutWidget_19 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_19.setGeometry(QtCore.QRect(40, 270, 181, 139))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget_19)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_24.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_13 = QtWidgets.QTextEdit(self.layoutWidget_19)
        self.textEdit_13.setObjectName("textEdit_13")
        self.verticalLayout_24.addWidget(self.textEdit_13)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(470, 460, 141, 71))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.layoutWidget_20 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_20.setGeometry(QtCore.QRect(40, 50, 461, 181))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.layoutWidget_20)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_20)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_25.addWidget(self.label_8)
        self.textEdit_14 = QtWidgets.QTextEdit(self.layoutWidget_20)
        self.textEdit_14.setObjectName("textEdit_14")
        self.verticalLayout_25.addWidget(self.textEdit_14)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(250, 270, 181, 131))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_26.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_15 = QtWidgets.QTextEdit(self.layoutWidget_6)
        self.textEdit_15.setObjectName("textEdit_15")
        self.verticalLayout_26.addWidget(self.textEdit_15)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(720, 500, 201, 51))
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(450, 270, 181, 131))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_27.addWidget(self.checkBox_3, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_16 = QtWidgets.QTextEdit(self.layoutWidget_7)
        self.textEdit_16.setObjectName("textEdit_16")
        self.verticalLayout_27.addWidget(self.textEdit_16)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(750, 410, 141, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.layoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_8.setGeometry(QtCore.QRect(40, 440, 181, 131))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_28.addWidget(self.checkBox_4, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_17 = QtWidgets.QTextEdit(self.layoutWidget_8)
        self.textEdit_17.setObjectName("textEdit_17")
        self.verticalLayout_28.addWidget(self.textEdit_17)
        self.layoutWidget_21 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_21.setGeometry(QtCore.QRect(630, 170, 271, 51))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.layoutWidget_21)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_21)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_29.addWidget(self.label_40)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_21)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_29.addWidget(self.lineEdit_7)
        self.layoutWidget_22 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_22.setGeometry(QtCore.QRect(630, 80, 271, 51))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.layoutWidget_22)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_22)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_30.addWidget(self.label_41)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_22)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_30.addWidget(self.lineEdit_25)
        self.layoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_9.setGeometry(QtCore.QRect(250, 440, 181, 131))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_31.addWidget(self.checkBox_5, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_18 = QtWidgets.QTextEdit(self.layoutWidget_9)
        self.textEdit_18.setObjectName("textEdit_18")
        self.verticalLayout_31.addWidget(self.textEdit_18)
        self.tabWidget_5.addTab(self.tab_3, "")
        self.tabWidget_4.addTab(self.tab_7, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.layoutWidget_23 = QtWidgets.QWidget(self.tab_19)
        self.layoutWidget_23.setGeometry(QtCore.QRect(80, 60, 491, 221))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.layoutWidget_23)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_23)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_32.addWidget(self.label_9)
        self.textEdit_19 = QtWidgets.QTextEdit(self.layoutWidget_23)
        self.textEdit_19.setObjectName("textEdit_19")
        self.verticalLayout_32.addWidget(self.textEdit_19)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_19)
        self.pushButton_28.setGeometry(QtCore.QRect(430, 460, 141, 51))
        self.pushButton_28.setObjectName("pushButton_28")
        self.label_42 = QtWidgets.QLabel(self.tab_19)
        self.label_42.setGeometry(QtCore.QRect(400, 560, 201, 51))
        self.label_42.setText("")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_19)
        self.pushButton_29.setGeometry(QtCore.QRect(370, 350, 281, 81))
        self.pushButton_29.setObjectName("pushButton_29")
        self.layoutWidget_24 = QtWidgets.QWidget(self.tab_19)
        self.layoutWidget_24.setGeometry(QtCore.QRect(660, 110, 271, 51))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.layoutWidget_24)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_24)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_33.addWidget(self.label_43)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_24)
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_33.addWidget(self.lineEdit_26)
        self.layoutWidget_25 = QtWidgets.QWidget(self.tab_19)
        self.layoutWidget_25.setGeometry(QtCore.QRect(660, 220, 271, 51))
        self.layoutWidget_25.setObjectName("layoutWidget_25")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.layoutWidget_25)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_25)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_34.addWidget(self.label_44)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_25)
        self.lineEdit_27.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_34.addWidget(self.lineEdit_27)
        self.tabWidget_4.addTab(self.tab_19, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_6.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 1011, 611))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget_6.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_2.setEnabled(False)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 240, 1011, 401))
        self.tableWidget_2.setRowCount(13)
        self.tableWidget_2.setColumnCount(10)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.layoutWidget = QtWidgets.QWidget(self.tab_12)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 391, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(self.tab_12)
        self.label_7.setGeometry(QtCore.QRect(170, 180, 181, 31))
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.tab_12)
        self.label_10.setGeometry(QtCore.QRect(480, 30, 461, 121))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.tabWidget_6.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_12 = QtWidgets.QLabel(self.tab_13)
        self.label_12.setGeometry(QtCore.QRect(580, 30, 261, 41))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_45 = QtWidgets.QLabel(self.tab_13)
        self.label_45.setGeometry(QtCore.QRect(240, 80, 161, 41))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.layoutWidget_27 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget_27.setGeometry(QtCore.QRect(300, 530, 181, 71))
        self.layoutWidget_27.setObjectName("layoutWidget_27")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.layoutWidget_27)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_27)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_22.addWidget(self.label_54)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget_27)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_22.addWidget(self.lineEdit_8)
        self.layoutWidget_29 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget_29.setGeometry(QtCore.QRect(550, 530, 181, 71))
        self.layoutWidget_29.setObjectName("layoutWidget_29")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.layoutWidget_29)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_29)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_35.addWidget(self.label_56)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_29)
        self.lineEdit_28.setText("")
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_35.addWidget(self.lineEdit_28)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_9.setGeometry(QtCore.QRect(820, 540, 151, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_57 = QtWidgets.QLabel(self.tab_13)
        self.label_57.setGeometry(QtCore.QRect(260, 620, 481, 41))
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.label_47 = QtWidgets.QLabel(self.tab_13)
        self.label_47.setGeometry(QtCore.QRect(510, 80, 251, 41))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 30, 329, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_3.addWidget(self.lineEdit_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget2.setGeometry(QtCore.QRect(110, 140, 801, 181))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_4.addWidget(self.label_46)
        self.textEdit_7 = QtWidgets.QTextEdit(self.layoutWidget2)
        self.textEdit_7.setObjectName("textEdit_7")
        self.horizontalLayout_4.addWidget(self.textEdit_7)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget3.setGeometry(QtCore.QRect(130, 340, 771, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_9.addWidget(self.radioButton_6, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_8 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_8.setObjectName("textEdit_8")
        self.verticalLayout_9.addWidget(self.textEdit_8)
        self.horizontalLayout_14.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_7 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_10.addWidget(self.radioButton_7, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_9 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_9.setObjectName("textEdit_9")
        self.verticalLayout_10.addWidget(self.textEdit_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_8 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_12.addWidget(self.radioButton_8, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_10 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_10.setObjectName("textEdit_10")
        self.verticalLayout_12.addWidget(self.textEdit_10)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_9 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_13.addWidget(self.radioButton_9, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_11 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_11.setObjectName("textEdit_11")
        self.verticalLayout_13.addWidget(self.textEdit_11)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.radioButton_10 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_15.addWidget(self.radioButton_10, 0, QtCore.Qt.AlignHCenter)
        self.textEdit_20 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_20.setObjectName("textEdit_20")
        self.verticalLayout_15.addWidget(self.textEdit_20)
        self.horizontalLayout_14.addLayout(self.verticalLayout_15)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 530, 181, 71))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_21.addWidget(self.label_53)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_21.addWidget(self.lineEdit_6)
        self.tabWidget_6.addTab(self.tab_13, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_14 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_14.setGeometry(QtCore.QRect(50, 70, 631, 561))
        self.tableWidget_14.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_14.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_14.setRowCount(15)
        self.tableWidget_14.setColumnCount(5)
        self.tableWidget_14.setObjectName("tableWidget_14")
        self.tableWidget_14.horizontalHeader().setVisible(False)
        self.tableWidget_14.verticalHeader().setVisible(False)
        self.tableWidget_15 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_15.setGeometry(QtCore.QRect(760, 250, 261, 381))
        self.tableWidget_15.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_15.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_15.setRowCount(10)
        self.tableWidget_15.setColumnCount(2)
        self.tableWidget_15.setObjectName("tableWidget_15")
        self.tableWidget_15.horizontalHeader().setVisible(False)
        self.tableWidget_15.verticalHeader().setVisible(False)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(770, 70, 231, 71))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_14.addWidget(self.lineEdit_9)
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_14.addWidget(self.pushButton_30)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(760, 160, 261, 61))
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_3.setEnabled(True)
        self.tableWidget_3.setGeometry(QtCore.QRect(140, 170, 111, 381))
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setDragDropOverwriteMode(True)
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_3.setRowCount(10)
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.label_13 = QtWidgets.QLabel(self.tab_8)
        self.label_13.setGeometry(QtCore.QRect(120, 110, 151, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(810, 170, 111, 191))
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_4.setRowCount(5)
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.label_15 = QtWidgets.QLabel(self.tab_8)
        self.label_15.setGeometry(QtCore.QRect(790, 110, 151, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.tab_8)
        self.label_17.setGeometry(QtCore.QRect(320, 590, 400, 51))
        self.label_17.setMinimumSize(QtCore.QSize(400, 50))
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget6.setGeometry(QtCore.QRect(300, 110, 461, 441))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_5.addWidget(self.lineEdit_10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_7.addWidget(self.lineEdit_12)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_6.addWidget(self.lineEdit_11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_8.addWidget(self.lineEdit_13)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_16.addWidget(self.pushButton_14)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_14)
        self.tabWidget_7.setGeometry(QtCore.QRect(20, 10, 1041, 711))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_5.setGeometry(QtCore.QRect(20, 60, 1011, 611))
        self.tableWidget_5.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_5.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_5.setRowCount(20)
        self.tableWidget_5.setColumnCount(10)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tabWidget_7.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.label_19 = QtWidgets.QLabel(self.tab_16)
        self.label_19.setGeometry(QtCore.QRect(20, 150, 211, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_16)
        self.tableWidget_7.setGeometry(QtCore.QRect(60, 200, 131, 381))
        self.tableWidget_7.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_7.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_7.setRowCount(10)
        self.tableWidget_7.setColumnCount(1)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.horizontalHeader().setVisible(False)
        self.tableWidget_7.verticalHeader().setVisible(False)
        self.label_18 = QtWidgets.QLabel(self.tab_16)
        self.label_18.setGeometry(QtCore.QRect(450, 80, 161, 51))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_16)
        self.label_20.setGeometry(QtCore.QRect(650, 20, 221, 51))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.layoutWidget_11 = QtWidgets.QWidget(self.tab_16)
        self.layoutWidget_11.setGeometry(QtCore.QRect(250, 180, 701, 401))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_67.setText("")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_42.addWidget(self.label_67)
        self.tableWidget_27 = QtWidgets.QTableWidget(self.layoutWidget_11)
        self.tableWidget_27.setRowCount(10)
        self.tableWidget_27.setColumnCount(1)
        self.tableWidget_27.setObjectName("tableWidget_27")
        self.tableWidget_27.horizontalHeader().setVisible(False)
        self.tableWidget_27.verticalHeader().setVisible(False)
        self.verticalLayout_42.addWidget(self.tableWidget_27)
        self.horizontalLayout_16.addLayout(self.verticalLayout_42)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_68 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_68.setText("")
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_43.addWidget(self.label_68)
        self.tableWidget_28 = QtWidgets.QTableWidget(self.layoutWidget_11)
        self.tableWidget_28.setRowCount(10)
        self.tableWidget_28.setColumnCount(1)
        self.tableWidget_28.setObjectName("tableWidget_28")
        self.tableWidget_28.horizontalHeader().setVisible(False)
        self.tableWidget_28.verticalHeader().setVisible(False)
        self.verticalLayout_43.addWidget(self.tableWidget_28)
        self.horizontalLayout_16.addLayout(self.verticalLayout_43)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_69 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_69.setText("")
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_44.addWidget(self.label_69)
        self.tableWidget_29 = QtWidgets.QTableWidget(self.layoutWidget_11)
        self.tableWidget_29.setRowCount(10)
        self.tableWidget_29.setColumnCount(1)
        self.tableWidget_29.setObjectName("tableWidget_29")
        self.tableWidget_29.horizontalHeader().setVisible(False)
        self.tableWidget_29.verticalHeader().setVisible(False)
        self.verticalLayout_44.addWidget(self.tableWidget_29)
        self.horizontalLayout_16.addLayout(self.verticalLayout_44)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_70 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_70.setText("")
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_45.addWidget(self.label_70)
        self.tableWidget_30 = QtWidgets.QTableWidget(self.layoutWidget_11)
        self.tableWidget_30.setRowCount(10)
        self.tableWidget_30.setColumnCount(1)
        self.tableWidget_30.setObjectName("tableWidget_30")
        self.tableWidget_30.horizontalHeader().setVisible(False)
        self.tableWidget_30.verticalHeader().setVisible(False)
        self.verticalLayout_45.addWidget(self.tableWidget_30)
        self.horizontalLayout_16.addLayout(self.verticalLayout_45)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_71.setText("")
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_46.addWidget(self.label_71)
        self.tableWidget_31 = QtWidgets.QTableWidget(self.layoutWidget_11)
        self.tableWidget_31.setRowCount(10)
        self.tableWidget_31.setColumnCount(1)
        self.tableWidget_31.setObjectName("tableWidget_31")
        self.tableWidget_31.horizontalHeader().setVisible(False)
        self.tableWidget_31.verticalHeader().setVisible(False)
        self.verticalLayout_46.addWidget(self.tableWidget_31)
        self.horizontalLayout_16.addLayout(self.verticalLayout_46)
        self.label_21 = QtWidgets.QLabel(self.tab_16)
        self.label_21.setGeometry(QtCore.QRect(450, 130, 301, 31))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_16)
        self.layoutWidget7.setGeometry(QtCore.QRect(150, 20, 411, 51))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_17.addWidget(self.pushButton_15)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_17.addWidget(self.lineEdit_14)
        self.tabWidget_7.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.label_22 = QtWidgets.QLabel(self.tab_17)
        self.label_22.setEnabled(False)
        self.label_22.setGeometry(QtCore.QRect(390, 110, 161, 51))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_17)
        self.label_23.setGeometry(QtCore.QRect(760, 180, 211, 31))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_17)
        self.label_24.setGeometry(QtCore.QRect(390, 80, 151, 31))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_17)
        self.tableWidget_8.setEnabled(False)
        self.tableWidget_8.setGeometry(QtCore.QRect(800, 270, 111, 201))
        self.tableWidget_8.setRowCount(5)
        self.tableWidget_8.setColumnCount(1)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.horizontalHeader().setVisible(False)
        self.tableWidget_8.verticalHeader().setVisible(False)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_17)
        self.tableWidget_9.setEnabled(False)
        self.tableWidget_9.setGeometry(QtCore.QRect(120, 280, 111, 311))
        self.tableWidget_9.setRowCount(10)
        self.tableWidget_9.setColumnCount(1)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.horizontalHeader().setVisible(False)
        self.tableWidget_9.verticalHeader().setVisible(False)
        self.label_25 = QtWidgets.QLabel(self.tab_17)
        self.label_25.setGeometry(QtCore.QRect(90, 190, 211, 31))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.layoutWidget_13 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget_13.setGeometry(QtCore.QRect(320, 160, 383, 441))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_17.setEnabled(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_9.addWidget(self.lineEdit_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_18.setEnabled(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_10.addWidget(self.pushButton_18)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_10.addWidget(self.lineEdit_17)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_19.setEnabled(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_11.addWidget(self.pushButton_19)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_11.addWidget(self.lineEdit_18)
        self.verticalLayout_17.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_20.setEnabled(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_12.addWidget(self.pushButton_20)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_12.addWidget(self.lineEdit_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_21.setEnabled(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_17.addWidget(self.pushButton_21)
        self.label_27 = QtWidgets.QLabel(self.tab_17)
        self.label_27.setGeometry(QtCore.QRect(140, 240, 111, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_17)
        self.label_28.setGeometry(QtCore.QRect(820, 230, 111, 21))
        self.label_28.setObjectName("label_28")
        self.label_26 = QtWidgets.QLabel(self.tab_17)
        self.label_26.setGeometry(QtCore.QRect(380, 620, 251, 41))
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.layoutWidget8 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget8.setGeometry(QtCore.QRect(330, 30, 303, 30))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_16.setEnabled(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_13.addWidget(self.pushButton_16)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_15.setEnabled(False)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_13.addWidget(self.lineEdit_15)
        self.tabWidget_7.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_22.setEnabled(False)
        self.pushButton_22.setGeometry(QtCore.QRect(240, 40, 241, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_20.setEnabled(False)
        self.lineEdit_20.setGeometry(QtCore.QRect(500, 50, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_18)
        self.tableWidget_10.setEnabled(False)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 150, 1011, 311))
        self.tableWidget_10.setRowCount(10)
        self.tableWidget_10.setColumnCount(10)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.horizontalHeader().setVisible(False)
        self.tableWidget_10.verticalHeader().setVisible(False)
        self.label_29 = QtWidgets.QLabel(self.tab_18)
        self.label_29.setGeometry(QtCore.QRect(380, 90, 211, 51))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_23.setEnabled(False)
        self.pushButton_23.setGeometry(QtCore.QRect(270, 490, 241, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_30 = QtWidgets.QLabel(self.tab_18)
        self.label_30.setGeometry(QtCore.QRect(400, 550, 171, 51))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_21.setEnabled(False)
        self.lineEdit_21.setGeometry(QtCore.QRect(540, 490, 111, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.tabWidget_7.addTab(self.tab_18, "")
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 1061, 711))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_16 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_16.setGeometry(QtCore.QRect(70, 80, 881, 491))
        self.tableWidget_16.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_16.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_16.setRowCount(13)
        self.tableWidget_16.setColumnCount(7)
        self.tableWidget_16.setObjectName("tableWidget_16")
        self.tableWidget_16.horizontalHeader().setVisible(False)
        self.tableWidget_16.verticalHeader().setVisible(False)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_16 = QtWidgets.QLabel(self.tab_9)
        self.label_16.setGeometry(QtCore.QRect(690, 380, 211, 71))
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 10, 1021, 661))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.tableWidget_17 = QtWidgets.QTableWidget(self.tab_25)
        self.tableWidget_17.setGeometry(QtCore.QRect(50, 40, 511, 561))
        self.tableWidget_17.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_17.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableWidget_17.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_17.setRowCount(15)
        self.tableWidget_17.setColumnCount(4)
        self.tableWidget_17.setObjectName("tableWidget_17")
        self.tableWidget_17.horizontalHeader().setVisible(False)
        self.tableWidget_17.verticalHeader().setVisible(False)
        self.tableWidget_20 = QtWidgets.QTableWidget(self.tab_25)
        self.tableWidget_20.setGeometry(QtCore.QRect(720, 220, 131, 41))
        self.tableWidget_20.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_20.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget_20.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_20.setRowCount(1)
        self.tableWidget_20.setColumnCount(1)
        self.tableWidget_20.setObjectName("tableWidget_20")
        self.tableWidget_20.horizontalHeader().setVisible(False)
        self.tableWidget_20.verticalHeader().setVisible(False)
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_25)
        self.pushButton_31.setGeometry(QtCore.QRect(660, 300, 249, 28))
        self.pushButton_31.setObjectName("pushButton_31")
        self.label_73 = QtWidgets.QLabel(self.tab_25)
        self.label_73.setGeometry(QtCore.QRect(680, 120, 201, 81))
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setWordWrap(True)
        self.label_73.setObjectName("label_73")
        self.tabWidget_3.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.label_49 = QtWidgets.QLabel(self.tab_26)
        self.label_49.setGeometry(QtCore.QRect(290, 20, 171, 31))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_59 = QtWidgets.QLabel(self.tab_26)
        self.label_59.setGeometry(QtCore.QRect(140, 50, 500, 50))
        self.label_59.setMinimumSize(QtCore.QSize(500, 50))
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.tableWidget_19 = QtWidgets.QTableWidget(self.tab_26)
        self.tableWidget_19.setGeometry(QtCore.QRect(810, 230, 121, 41))
        self.tableWidget_19.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_19.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget_19.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_19.setRowCount(1)
        self.tableWidget_19.setColumnCount(1)
        self.tableWidget_19.setObjectName("tableWidget_19")
        self.tableWidget_19.horizontalHeader().setVisible(False)
        self.tableWidget_19.verticalHeader().setVisible(False)
        self.label_60 = QtWidgets.QLabel(self.tab_26)
        self.label_60.setGeometry(QtCore.QRect(780, 130, 201, 81))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setWordWrap(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_26)
        self.label_61.setGeometry(QtCore.QRect(790, 400, 181, 81))
        self.label_61.setText("")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_26)
        self.pushButton_33.setGeometry(QtCore.QRect(770, 290, 221, 71))
        self.pushButton_33.setObjectName("pushButton_33")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_26)
        self.tableWidget_6.setGeometry(QtCore.QRect(50, 110, 631, 491))
        self.tableWidget_6.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_6.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableWidget_6.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_6.setRowCount(13)
        self.tableWidget_6.setColumnCount(5)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.horizontalHeader().setVisible(False)
        self.tableWidget_6.verticalHeader().setVisible(False)
        self.tabWidget_3.addTab(self.tab_26, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.label_62 = QtWidgets.QLabel(self.tab_27)
        self.label_62.setGeometry(QtCore.QRect(380, 30, 201, 41))
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_27)
        self.label_63.setGeometry(QtCore.QRect(220, 80, 161, 41))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.tableWidget_25 = QtWidgets.QTableWidget(self.tab_27)
        self.tableWidget_25.setGeometry(QtCore.QRect(240, 220, 131, 381))
        self.tableWidget_25.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_25.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableWidget_25.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_25.setRowCount(10)
        self.tableWidget_25.setColumnCount(1)
        self.tableWidget_25.setObjectName("tableWidget_25")
        self.tableWidget_25.horizontalHeader().setVisible(False)
        self.tableWidget_25.verticalHeader().setVisible(False)
        self.label_64 = QtWidgets.QLabel(self.tab_27)
        self.label_64.setGeometry(QtCore.QRect(180, 140, 271, 51))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.tableWidget_26 = QtWidgets.QTableWidget(self.tab_27)
        self.tableWidget_26.setGeometry(QtCore.QRect(650, 290, 131, 41))
        self.tableWidget_26.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_26.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget_26.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_26.setRowCount(1)
        self.tableWidget_26.setColumnCount(1)
        self.tableWidget_26.setObjectName("tableWidget_26")
        self.tableWidget_26.horizontalHeader().setVisible(False)
        self.tableWidget_26.verticalHeader().setVisible(False)
        self.label_65 = QtWidgets.QLabel(self.tab_27)
        self.label_65.setGeometry(QtCore.QRect(600, 190, 241, 71))
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setWordWrap(True)
        self.label_65.setObjectName("label_65")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_27)
        self.pushButton_34.setGeometry(QtCore.QRect(630, 360, 181, 61))
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_66 = QtWidgets.QLabel(self.tab_27)
        self.label_66.setGeometry(QtCore.QRect(630, 450, 191, 71))
        self.label_66.setText("")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setWordWrap(True)
        self.label_66.setObjectName("label_66")
        self.label_50 = QtWidgets.QLabel(self.tab_27)
        self.label_50.setGeometry(QtCore.QRect(600, 80, 191, 41))
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.tabWidget_3.addTab(self.tab_27, "")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.tableWidget_18 = QtWidgets.QTableWidget(self.tab_24)
        self.tableWidget_18.setGeometry(QtCore.QRect(40, 50, 631, 561))
        self.tableWidget_18.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_18.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableWidget_18.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_18.setRowCount(15)
        self.tableWidget_18.setColumnCount(5)
        self.tableWidget_18.setObjectName("tableWidget_18")
        self.tableWidget_18.horizontalHeader().setVisible(False)
        self.tableWidget_18.verticalHeader().setVisible(False)
        self.label_48 = QtWidgets.QLabel(self.tab_24)
        self.label_48.setGeometry(QtCore.QRect(770, 330, 201, 61))
        self.label_48.setText("")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.pushButton_32 = QtWidgets.QPushButton(self.tab_24)
        self.pushButton_32.setGeometry(QtCore.QRect(770, 360, 241, 81))
        self.pushButton_32.setObjectName("pushButton_32")
        self.tableWidget_21 = QtWidgets.QTableWidget(self.tab_24)
        self.tableWidget_21.setGeometry(QtCore.QRect(810, 260, 131, 41))
        self.tableWidget_21.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_21.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget_21.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_21.setRowCount(1)
        self.tableWidget_21.setColumnCount(1)
        self.tableWidget_21.setObjectName("tableWidget_21")
        self.tableWidget_21.horizontalHeader().setVisible(False)
        self.tableWidget_21.verticalHeader().setVisible(False)
        self.label_74 = QtWidgets.QLabel(self.tab_24)
        self.label_74.setGeometry(QtCore.QRect(790, 140, 201, 81))
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setWordWrap(True)
        self.label_74.setObjectName("label_74")
        self.tabWidget_2.addTab(self.tab_24, "")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.tab_21)
        self.tabWidget_8.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_8.setObjectName("tabWidget_8")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.tableWidget_11 = QtWidgets.QTableWidget(self.tab_22)
        self.tableWidget_11.setGeometry(QtCore.QRect(20, 50, 1011, 611))
        self.tableWidget_11.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_11.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_11.setRowCount(20)
        self.tableWidget_11.setColumnCount(10)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.horizontalHeader().setVisible(False)
        self.tableWidget_11.verticalHeader().setVisible(False)
        self.tabWidget_8.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_23)
        self.pushButton_24.setGeometry(QtCore.QRect(100, 20, 291, 51))
        self.pushButton_24.setObjectName("pushButton_24")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_23)
        self.lineEdit_22.setGeometry(QtCore.QRect(420, 30, 111, 31))
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.tableWidget_12 = QtWidgets.QTableWidget(self.tab_23)
        self.tableWidget_12.setGeometry(QtCore.QRect(50, 200, 131, 191))
        self.tableWidget_12.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_12.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_12.setRowCount(5)
        self.tableWidget_12.setColumnCount(1)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.horizontalHeader().setVisible(False)
        self.tableWidget_12.verticalHeader().setVisible(False)
        self.label_31 = QtWidgets.QLabel(self.tab_23)
        self.label_31.setGeometry(QtCore.QRect(40, 150, 161, 31))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_23)
        self.label_32.setGeometry(QtCore.QRect(650, 20, 300, 51))
        self.label_32.setMinimumSize(QtCore.QSize(300, 50))
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_23)
        self.label_33.setGeometry(QtCore.QRect(370, 80, 211, 41))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.tableWidget_13 = QtWidgets.QTableWidget(self.tab_23)
        self.tableWidget_13.setGeometry(QtCore.QRect(280, 280, 131, 381))
        self.tableWidget_13.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_13.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableWidget_13.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_13.setRowCount(10)
        self.tableWidget_13.setColumnCount(1)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.horizontalHeader().setVisible(False)
        self.tableWidget_13.verticalHeader().setVisible(False)
        self.layoutWidget9 = QtWidgets.QWidget(self.tab_23)
        self.layoutWidget9.setGeometry(QtCore.QRect(240, 140, 266, 61))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget9)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_18.addWidget(self.pushButton_25)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_18.addWidget(self.lineEdit_23)
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_23)
        self.pushButton_26.setGeometry(QtCore.QRect(450, 440, 201, 61))
        self.pushButton_26.setObjectName("pushButton_26")
        self.tableWidget_22 = QtWidgets.QTableWidget(self.tab_23)
        self.tableWidget_22.setGeometry(QtCore.QRect(490, 360, 121, 41))
        self.tableWidget_22.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_22.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget_22.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_22.setRowCount(1)
        self.tableWidget_22.setColumnCount(1)
        self.tableWidget_22.setObjectName("tableWidget_22")
        self.tableWidget_22.horizontalHeader().setVisible(False)
        self.tableWidget_22.verticalHeader().setVisible(False)
        self.label_55 = QtWidgets.QLabel(self.tab_23)
        self.label_55.setGeometry(QtCore.QRect(450, 260, 201, 81))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.layoutWidget10 = QtWidgets.QWidget(self.tab_23)
        self.layoutWidget10.setGeometry(QtCore.QRect(700, 140, 311, 491))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_15.addWidget(self.label_34)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_58.setText("")
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_15.addWidget(self.label_58)
        self.verticalLayout_19.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_72.setText("")
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_18.addWidget(self.label_72)
        self.verticalLayout_19.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_19.addWidget(self.label_39)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_75.setText("")
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_19.addWidget(self.label_75)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_20.addWidget(self.label_38)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_76.setText("")
        self.label_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_20.addWidget(self.label_76)
        self.verticalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_21.addWidget(self.label_36)
        self.label_77 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_77.setText("")
        self.label_77.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_21.addWidget(self.label_77)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_22.addWidget(self.label_51)
        self.label_78 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_78.setText("")
        self.label_78.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_22.addWidget(self.label_78)
        self.verticalLayout_19.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_23.addWidget(self.label_52)
        self.label_79 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_79.setText("")
        self.label_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_23.addWidget(self.label_79)
        self.verticalLayout_19.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_24.addWidget(self.label_37)
        self.label_80 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_80.setText("")
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_24.addWidget(self.label_80)
        self.verticalLayout_19.addLayout(self.horizontalLayout_24)
        self.label_81 = QtWidgets.QLabel(self.tab_23)
        self.label_81.setGeometry(QtCore.QRect(270, 220, 181, 31))
        self.label_81.setText("")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.tabWidget_8.addTab(self.tab_23, "")
        self.tabWidget.addTab(self.tab_21, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 350, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_27.setGeometry(QtCore.QRect(440, 290, 151, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.tabWidget.addTab(self.tab_20, "")
        TeacherMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeacherMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 26))
        self.menubar.setObjectName("menubar")
        TeacherMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeacherMainWindow)
        self.statusbar.setObjectName("statusbar")
        TeacherMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TeacherMainWindow)
        self.tabWidget.setCurrentIndex(6)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(1)
        self.tabWidget_6.setCurrentIndex(2)
        self.tabWidget_7.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        self.tabWidget_8.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TeacherMainWindow)

    def retranslateUi(self, TeacherMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TeacherMainWindow.setWindowTitle(_translate("TeacherMainWindow", "Teacher Application"))
        self.pushButton.setText(_translate("TeacherMainWindow", "Create Question"))
        self.label_2.setText(_translate("TeacherMainWindow", "Please Select The Correct Answer Before Clicking On Create Question Button"))
        self.radioButton_2.setText(_translate("TeacherMainWindow", "Option B"))
        self.radioButton_3.setText(_translate("TeacherMainWindow", "Option D"))
        self.textEdit_4.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_4.setText(_translate("TeacherMainWindow", "Option E"))
        self.radioButton_5.setText(_translate("TeacherMainWindow", "Option C"))
        self.pushButton_5.setText(_translate("TeacherMainWindow", "Preview Question Before Creating"))
        self.radioButton.setText(_translate("TeacherMainWindow", "Option A "))
        self.label.setText(_translate("TeacherMainWindow", "Question Body"))
        self.label_3.setText(_translate("TeacherMainWindow", "What is the Year Level Of The Question?"))
        self.label_5.setText(_translate("TeacherMainWindow", "What is the Question Phrase Tag?"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_10), _translate("TeacherMainWindow", "Single Answer"))
        self.pushButton_6.setText(_translate("TeacherMainWindow", "Preview Question Before Creating"))
        self.checkBox.setText(_translate("TeacherMainWindow", "Option A"))
        self.label_6.setText(_translate("TeacherMainWindow", "Please Select The Correct Answers Before Clicking On Create Question Button"))
        self.label_8.setText(_translate("TeacherMainWindow", "Question Body"))
        self.checkBox_2.setText(_translate("TeacherMainWindow", "Option B"))
        self.checkBox_3.setText(_translate("TeacherMainWindow", "Option C"))
        self.pushButton_7.setText(_translate("TeacherMainWindow", "Create Question"))
        self.checkBox_4.setText(_translate("TeacherMainWindow", "Option D"))
        self.textEdit_17.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_40.setText(_translate("TeacherMainWindow", "What is the Question Phrase Tag?"))
        self.label_41.setText(_translate("TeacherMainWindow", "What is the Year Level Of The Question?"))
        self.checkBox_5.setText(_translate("TeacherMainWindow", "Option E"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_3), _translate("TeacherMainWindow", "Multiple Answers"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("TeacherMainWindow", "Multiple Choice"))
        self.label_9.setText(_translate("TeacherMainWindow", "Essay Question Body"))
        self.pushButton_28.setText(_translate("TeacherMainWindow", "Create Question"))
        self.pushButton_29.setText(_translate("TeacherMainWindow", "Preview Question Before Creating"))
        self.label_43.setText(_translate("TeacherMainWindow", "What is the Year Level Of The Question?"))
        self.label_44.setText(_translate("TeacherMainWindow", "What is the Question Phrase Tag?"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_19), _translate("TeacherMainWindow", "Essay"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TeacherMainWindow", "Create Question"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_11), _translate("TeacherMainWindow", "The Bank"))
        self.pushButton_2.setText(_translate("TeacherMainWindow", "Search By Year Level Between 1 and 13"))
        self.pushButton_3.setText(_translate("TeacherMainWindow", "Search By Phrase"))
        self.label_10.setText(_translate("TeacherMainWindow", "Please Choose A Phrase From This List:"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_12), _translate("TeacherMainWindow", "Search The Bank By Tag"))
        self.label_45.setText(_translate("TeacherMainWindow", "Question ID: "))
        self.label_54.setText(_translate("TeacherMainWindow", "Phrase Tag"))
        self.label_56.setText(_translate("TeacherMainWindow", "Question Points"))
        self.pushButton_9.setText(_translate("TeacherMainWindow", "Modify"))
        self.label_47.setText(_translate("TeacherMainWindow", "Question Type:"))
        self.pushButton_8.setText(_translate("TeacherMainWindow", "Load Question Details By ID"))
        self.label_46.setText(_translate("TeacherMainWindow", "Question Body: "))
        self.textEdit_7.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_6.setText(_translate("TeacherMainWindow", "A"))
        self.textEdit_8.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_7.setText(_translate("TeacherMainWindow", "B"))
        self.textEdit_9.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_8.setText(_translate("TeacherMainWindow", "C"))
        self.textEdit_10.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_9.setText(_translate("TeacherMainWindow", "D"))
        self.textEdit_11.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_10.setText(_translate("TeacherMainWindow", "E"))
        self.textEdit_20.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_53.setText(_translate("TeacherMainWindow", "Year Level"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_13), _translate("TeacherMainWindow", "View Or Modify Question"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TeacherMainWindow", "Questions Bank"))
        self.pushButton_30.setText(_translate("TeacherMainWindow", "View Students In School Class By ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("TeacherMainWindow", "School Classes Bank"))
        self.label_13.setText(_translate("TeacherMainWindow", "Questions In Exam (Maximum 10)"))
        self.label_15.setText(_translate("TeacherMainWindow", "School Classes In Exam (Maximum 5) "))
        self.pushButton_10.setText(_translate("TeacherMainWindow", "Add Question To Exam By Question ID"))
        self.pushButton_12.setText(_translate("TeacherMainWindow", "Remove Question From Exam By Question ID"))
        self.pushButton_11.setText(_translate("TeacherMainWindow", "Add School Class To Exam By School Class ID"))
        self.pushButton_13.setText(_translate("TeacherMainWindow", "Remove School Class From Exam By School Class ID"))
        self.pushButton_14.setText(_translate("TeacherMainWindow", "Create Exam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("TeacherMainWindow", "Create Exam"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_15), _translate("TeacherMainWindow", "All Exams"))
        self.label_19.setText(_translate("TeacherMainWindow", "Questions In Exam: "))
        self.label_18.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_21.setText(_translate("TeacherMainWindow", "Students In School Classes In This Exam:"))
        self.pushButton_15.setText(_translate("TeacherMainWindow", "View Exam Details By ID"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_16), _translate("TeacherMainWindow", "View Exam Details"))
        self.label_22.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_23.setText(_translate("TeacherMainWindow", "Number Of School Classes In Exam: "))
        self.label_25.setText(_translate("TeacherMainWindow", "Number Of Questions In Exam: "))
        self.pushButton_17.setText(_translate("TeacherMainWindow", "Add Question To Exam By Question ID"))
        self.pushButton_18.setText(_translate("TeacherMainWindow", "Remove Question From Exam By Question ID"))
        self.pushButton_19.setText(_translate("TeacherMainWindow", "Add School Class To Exam By School Class ID"))
        self.pushButton_20.setText(_translate("TeacherMainWindow", "Remove School Class From Exam By School Class ID"))
        self.pushButton_21.setText(_translate("TeacherMainWindow", "Modify Exam"))
        self.label_27.setText(_translate("TeacherMainWindow", "(Maximum 10)"))
        self.label_28.setText(_translate("TeacherMainWindow", "(Maximum 5)"))
        self.pushButton_16.setText(_translate("TeacherMainWindow", "Modify Exam Details By Exam ID"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_17), _translate("TeacherMainWindow", "Modify Exam Details"))
        self.pushButton_22.setText(_translate("TeacherMainWindow", "De-Activate Exam By Exam ID"))
        self.pushButton_23.setText(_translate("TeacherMainWindow", "Re-Activate Exam By Exam ID"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_18), _translate("TeacherMainWindow", "Exam Activation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("TeacherMainWindow", "Exams Bank"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("TeacherMainWindow", "Current Not Completed Exams"))
        self.pushButton_31.setText(_translate("TeacherMainWindow", "Mark Exam On Next Page"))
        self.label_73.setText(_translate("TeacherMainWindow", "Drag And Drop Exam In To Box Below To Mark Exam "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_25), _translate("TeacherMainWindow", "Ready To Be Marked Exams Bank"))
        self.label_49.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_59.setText(_translate("TeacherMainWindow", "Students With Outstanding Questions Answers To Be Marked"))
        self.label_60.setText(_translate("TeacherMainWindow", "Drag And Drop Student In To Box Below To Mark His/Her Outstanding Questions Answers"))
        self.pushButton_33.setText(_translate("TeacherMainWindow", "Mark Student\'s Questions Answers \n"
" On Next Page"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_26), _translate("TeacherMainWindow", "Marking Exam"))
        self.label_62.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_63.setText(_translate("TeacherMainWindow", "Student ID: "))
        self.label_64.setText(_translate("TeacherMainWindow", "Outstanding Questions To Be Marked"))
        self.label_65.setText(_translate("TeacherMainWindow", "Drag And Drop Question In To Box Below To Mark Question"))
        self.pushButton_34.setText(_translate("TeacherMainWindow", "Mark Question"))
        self.label_50.setText(_translate("TeacherMainWindow", "Student Name: "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_27), _translate("TeacherMainWindow", "Mark Student\'s Questions Answers"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("TeacherMainWindow", "Exams Ready To Be Marked"))
        self.pushButton_32.setText(_translate("TeacherMainWindow", "Release Exam Result"))
        self.label_74.setText(_translate("TeacherMainWindow", "Drag And Drop Exam In To Box Below To Release Exam Result"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_24), _translate("TeacherMainWindow", "Exams Already Marked"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("TeacherMainWindow", "Exams In Progress"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_22), _translate("TeacherMainWindow", "All Exam Results"))
        self.pushButton_24.setText(_translate("TeacherMainWindow", "Load Exam Results Details By Exam Result ID"))
        self.label_31.setText(_translate("TeacherMainWindow", "School Classes In The Exam"))
        self.label_33.setText(_translate("TeacherMainWindow", "Exam Result ID: "))
        self.pushButton_25.setText(_translate("TeacherMainWindow", "View School Class Details By School Class ID"))
        self.pushButton_26.setText(_translate("TeacherMainWindow", "View Student Exam Result"))
        self.label_55.setText(_translate("TeacherMainWindow", "Drag And Drop Student In To Box Below To View Exam Result"))
        self.label_34.setText(_translate("TeacherMainWindow", "Student ID: "))
        self.label_35.setText(_translate("TeacherMainWindow", "Student Full Name: "))
        self.label_39.setText(_translate("TeacherMainWindow", "Date Of Birth: "))
        self.label_38.setText(_translate("TeacherMainWindow", "School Class ID: "))
        self.label_36.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_51.setText(_translate("TeacherMainWindow", "Total Available Points: "))
        self.label_52.setText(_translate("TeacherMainWindow", "Total Points Gained: "))
        self.label_37.setText(_translate("TeacherMainWindow", "Average Percentage Mark:  "))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_23), _translate("TeacherMainWindow", "View Exam Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_21), _translate("TeacherMainWindow", "Exam Results Bank"))
        self.pushButton_4.setText(_translate("TeacherMainWindow", "Close"))
        self.pushButton_27.setText(_translate("TeacherMainWindow", "Log Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_20), _translate("TeacherMainWindow", "Close Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeacherMainWindow = QtWidgets.QMainWindow()
    ui = Ui_TeacherMainWindow()
    ui.setupUi(TeacherMainWindow)
    TeacherMainWindow.show()
    sys.exit(app.exec_())

