# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeacherGUIQtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TeacherMainWindow(object):
    def setupUi(self, TeacherMainWindow):
        TeacherMainWindow.setObjectName("TeacherMainWindow")
        TeacherMainWindow.resize(1132, 875)
        self.centralwidget = QtWidgets.QWidget(TeacherMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1081, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_5.setGeometry(QtCore.QRect(10, 10, 1021, 661))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget_6.setGeometry(QtCore.QRect(90, 60, 461, 181))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.textEdit_7 = QtWidgets.QTextEdit(self.layoutWidget_6)
        self.textEdit_7.setObjectName("textEdit_7")
        self.verticalLayout_9.addWidget(self.textEdit_7)
        self.layoutWidget_9 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget_9.setGeometry(QtCore.QRect(640, 100, 271, 51))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_12.addWidget(self.lineEdit_5)
        self.layoutWidget_10 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget_10.setGeometry(QtCore.QRect(640, 220, 271, 51))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_14.addWidget(self.lineEdit_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_6.setGeometry(QtCore.QRect(640, 330, 271, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 420, 141, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setGeometry(QtCore.QRect(240, 440, 141, 71))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_9)
        self.label_11.setGeometry(QtCore.QRect(670, 490, 201, 51))
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.layoutWidget = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 300, 91, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_10.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_10.addWidget(self.radioButton_7)
        self.tabWidget_5.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton = QtWidgets.QPushButton(self.tab_10)
        self.pushButton.setGeometry(QtCore.QRect(740, 380, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab_10)
        self.label_2.setGeometry(QtCore.QRect(460, 430, 141, 71))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(240, 240, 181, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_3 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_2.addWidget(self.textEdit_3)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 410, 181, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_3.addWidget(self.radioButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_4 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_3.addWidget(self.textEdit_4)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_4.setGeometry(QtCore.QRect(240, 410, 181, 131))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_5 = QtWidgets.QTextEdit(self.layoutWidget_4)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_4.addWidget(self.textEdit_5)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_5.setGeometry(QtCore.QRect(440, 240, 181, 131))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_5.addWidget(self.radioButton_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_6 = QtWidgets.QTextEdit(self.layoutWidget_5)
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_5.addWidget(self.textEdit_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_5.setGeometry(QtCore.QRect(670, 270, 281, 81))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.tab_10)
        self.label_4.setGeometry(QtCore.QRect(710, 470, 201, 51))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.layoutWidget_15 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_15.setGeometry(QtCore.QRect(30, 240, 181, 131))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget_15)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget_15)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.layoutWidget_16 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_16.setGeometry(QtCore.QRect(30, 20, 461, 181))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_16)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget_16)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget_16)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.layoutWidget_17 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_17.setGeometry(QtCore.QRect(620, 50, 271, 51))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_17)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_17)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_7.addWidget(self.lineEdit_3)
        self.layoutWidget_18 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget_18.setGeometry(QtCore.QRect(620, 140, 271, 51))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_18)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_8.addWidget(self.lineEdit_4)
        self.tabWidget_5.addTab(self.tab_10, "")
        self.tabWidget_4.addTab(self.tab_7, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.spinBox = QtWidgets.QSpinBox(self.tab_19)
        self.spinBox.setGeometry(QtCore.QRect(180, 240, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.tabWidget_4.addTab(self.tab_19, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_6.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 1011, 611))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget_6.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 240, 1011, 401))
        self.tableWidget_2.setRowCount(13)
        self.tableWidget_2.setColumnCount(10)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_12)
        self.layoutWidget1.setGeometry(QtCore.QRect(320, 60, 391, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.tabWidget_6.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_12 = QtWidgets.QLabel(self.tab_13)
        self.label_12.setGeometry(QtCore.QRect(390, 370, 201, 71))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_13)
        self.layoutWidget2.setGeometry(QtCore.QRect(300, 150, 391, 171))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_3.addWidget(self.lineEdit_8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_4.addWidget(self.lineEdit_9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.tabWidget_6.addTab(self.tab_13, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_3.setGeometry(QtCore.QRect(130, 230, 111, 311))
        self.tableWidget_3.setRowCount(10)
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.label_13 = QtWidgets.QLabel(self.tab_8)
        self.label_13.setGeometry(QtCore.QRect(90, 140, 211, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setGeometry(QtCore.QRect(160, 190, 111, 21))
        self.label_14.setObjectName("label_14")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(810, 230, 111, 311))
        self.tableWidget_4.setRowCount(10)
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.label_15 = QtWidgets.QLabel(self.tab_8)
        self.label_15.setGeometry(QtCore.QRect(760, 150, 211, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_8)
        self.label_16.setGeometry(QtCore.QRect(830, 190, 111, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_8)
        self.label_17.setGeometry(QtCore.QRect(410, 600, 241, 51))
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(340, 110, 383, 441))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_5.addWidget(self.lineEdit_10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_7.addWidget(self.lineEdit_12)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_6.addWidget(self.lineEdit_11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_8.addWidget(self.lineEdit_13)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_16.addWidget(self.pushButton_14)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_14)
        self.tabWidget_7.setGeometry(QtCore.QRect(20, 10, 1041, 711))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_5.setGeometry(QtCore.QRect(20, 60, 1011, 611))
        self.tableWidget_5.setRowCount(20)
        self.tableWidget_5.setColumnCount(10)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tabWidget_7.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_16)
        self.pushButton_15.setGeometry(QtCore.QRect(280, 50, 171, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_16)
        self.lineEdit_14.setGeometry(QtCore.QRect(500, 50, 161, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_16)
        self.tableWidget_6.setGeometry(QtCore.QRect(610, 320, 111, 311))
        self.tableWidget_6.setRowCount(10)
        self.tableWidget_6.setColumnCount(1)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.horizontalHeader().setVisible(False)
        self.tableWidget_6.verticalHeader().setVisible(False)
        self.label_19 = QtWidgets.QLabel(self.tab_16)
        self.label_19.setGeometry(QtCore.QRect(190, 230, 211, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_16)
        self.tableWidget_7.setGeometry(QtCore.QRect(250, 320, 111, 311))
        self.tableWidget_7.setRowCount(10)
        self.tableWidget_7.setColumnCount(1)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.horizontalHeader().setVisible(False)
        self.tableWidget_7.verticalHeader().setVisible(False)
        self.label_21 = QtWidgets.QLabel(self.tab_16)
        self.label_21.setGeometry(QtCore.QRect(580, 230, 211, 31))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.label_18 = QtWidgets.QLabel(self.tab_16)
        self.label_18.setGeometry(QtCore.QRect(390, 200, 161, 51))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_16)
        self.label_20.setGeometry(QtCore.QRect(410, 130, 151, 31))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tabWidget_7.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.label_22 = QtWidgets.QLabel(self.tab_17)
        self.label_22.setGeometry(QtCore.QRect(390, 110, 161, 51))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_17)
        self.label_23.setGeometry(QtCore.QRect(760, 180, 211, 31))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_17)
        self.label_24.setGeometry(QtCore.QRect(390, 80, 151, 31))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_17)
        self.tableWidget_8.setGeometry(QtCore.QRect(800, 270, 111, 311))
        self.tableWidget_8.setRowCount(10)
        self.tableWidget_8.setColumnCount(1)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.horizontalHeader().setVisible(False)
        self.tableWidget_8.verticalHeader().setVisible(False)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_17)
        self.tableWidget_9.setGeometry(QtCore.QRect(120, 280, 111, 311))
        self.tableWidget_9.setRowCount(10)
        self.tableWidget_9.setColumnCount(1)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.horizontalHeader().setVisible(False)
        self.tableWidget_9.verticalHeader().setVisible(False)
        self.label_25 = QtWidgets.QLabel(self.tab_17)
        self.label_25.setGeometry(QtCore.QRect(90, 190, 211, 31))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.layoutWidget_13 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget_13.setGeometry(QtCore.QRect(320, 160, 383, 441))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_9.addWidget(self.lineEdit_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_10.addWidget(self.pushButton_18)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_10.addWidget(self.lineEdit_17)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_11.addWidget(self.pushButton_19)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_11.addWidget(self.lineEdit_18)
        self.verticalLayout_17.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_12.addWidget(self.pushButton_20)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_12.addWidget(self.lineEdit_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_17.addWidget(self.pushButton_21)
        self.label_27 = QtWidgets.QLabel(self.tab_17)
        self.label_27.setGeometry(QtCore.QRect(140, 240, 111, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_17)
        self.label_28.setGeometry(QtCore.QRect(820, 230, 111, 21))
        self.label_28.setObjectName("label_28")
        self.label_26 = QtWidgets.QLabel(self.tab_17)
        self.label_26.setGeometry(QtCore.QRect(380, 620, 251, 41))
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget4.setGeometry(QtCore.QRect(330, 30, 303, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_13.addWidget(self.pushButton_16)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_13.addWidget(self.lineEdit_15)
        self.tabWidget_7.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_22.setGeometry(QtCore.QRect(240, 40, 241, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_20.setGeometry(QtCore.QRect(500, 50, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_18)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 150, 1011, 311))
        self.tableWidget_10.setRowCount(10)
        self.tableWidget_10.setColumnCount(10)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.horizontalHeader().setVisible(False)
        self.tableWidget_10.verticalHeader().setVisible(False)
        self.label_29 = QtWidgets.QLabel(self.tab_18)
        self.label_29.setGeometry(QtCore.QRect(380, 90, 211, 51))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_18)
        self.pushButton_23.setGeometry(QtCore.QRect(270, 490, 241, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_30 = QtWidgets.QLabel(self.tab_18)
        self.label_30.setGeometry(QtCore.QRect(400, 550, 171, 51))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_18)
        self.lineEdit_21.setGeometry(QtCore.QRect(540, 490, 111, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.tabWidget_7.addTab(self.tab_18, "")
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.tab_21)
        self.tabWidget_8.setGeometry(QtCore.QRect(10, 10, 1051, 711))
        self.tabWidget_8.setObjectName("tabWidget_8")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.tableWidget_11 = QtWidgets.QTableWidget(self.tab_22)
        self.tableWidget_11.setGeometry(QtCore.QRect(20, 50, 1011, 611))
        self.tableWidget_11.setRowCount(20)
        self.tableWidget_11.setColumnCount(10)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.horizontalHeader().setVisible(False)
        self.tableWidget_11.verticalHeader().setVisible(False)
        self.tabWidget_8.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_23)
        self.pushButton_24.setGeometry(QtCore.QRect(280, 20, 221, 41))
        self.pushButton_24.setObjectName("pushButton_24")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_23)
        self.lineEdit_22.setGeometry(QtCore.QRect(520, 30, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.tableWidget_12 = QtWidgets.QTableWidget(self.tab_23)
        self.tableWidget_12.setGeometry(QtCore.QRect(80, 310, 111, 311))
        self.tableWidget_12.setRowCount(10)
        self.tableWidget_12.setColumnCount(1)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.horizontalHeader().setVisible(False)
        self.tableWidget_12.verticalHeader().setVisible(False)
        self.label_31 = QtWidgets.QLabel(self.tab_23)
        self.label_31.setGeometry(QtCore.QRect(60, 200, 161, 31))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_23)
        self.label_32.setGeometry(QtCore.QRect(390, 70, 181, 41))
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_23)
        self.label_33.setGeometry(QtCore.QRect(380, 110, 211, 41))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.tableWidget_13 = QtWidgets.QTableWidget(self.tab_23)
        self.tableWidget_13.setGeometry(QtCore.QRect(370, 310, 211, 311))
        self.tableWidget_13.setRowCount(10)
        self.tableWidget_13.setColumnCount(2)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.horizontalHeader().setVisible(False)
        self.tableWidget_13.verticalHeader().setVisible(False)
        self.layoutWidget_14 = QtWidgets.QWidget(self.tab_23)
        self.layoutWidget_14.setGeometry(QtCore.QRect(700, 200, 264, 61))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget_14)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_19.addWidget(self.pushButton_26)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_19.addWidget(self.lineEdit_24)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_23)
        self.layoutWidget5.setGeometry(QtCore.QRect(350, 200, 266, 61))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_18.addWidget(self.pushButton_25)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_18.addWidget(self.lineEdit_23)
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_23)
        self.layoutWidget6.setGeometry(QtCore.QRect(700, 310, 311, 321))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_20.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_20.addWidget(self.label_35)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_20.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_20.addWidget(self.label_38)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_20.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_20.addWidget(self.label_37)
        self.tabWidget_8.addTab(self.tab_23, "")
        self.tabWidget.addTab(self.tab_21, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 350, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_27.setGeometry(QtCore.QRect(440, 290, 151, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.tabWidget.addTab(self.tab_20, "")
        TeacherMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeacherMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 26))
        self.menubar.setObjectName("menubar")
        TeacherMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeacherMainWindow)
        self.statusbar.setObjectName("statusbar")
        TeacherMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TeacherMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.tabWidget_8.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TeacherMainWindow)

    def retranslateUi(self, TeacherMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TeacherMainWindow.setWindowTitle(_translate("TeacherMainWindow", "Teacher Application"))
        self.label_6.setText(_translate("TeacherMainWindow", "Question Body"))
        self.label_7.setText(_translate("TeacherMainWindow", "What is the Year Level Of The Question?"))
        self.label_9.setText(_translate("TeacherMainWindow", "What is the Question Phrase Tag?"))
        self.pushButton_6.setText(_translate("TeacherMainWindow", "Preview Question Before Creating"))
        self.pushButton_7.setText(_translate("TeacherMainWindow", "Create Question"))
        self.label_10.setText(_translate("TeacherMainWindow", "Please Select The Correct Answer Before Clicking On Create Question Button"))
        self.radioButton_6.setText(_translate("TeacherMainWindow", "True"))
        self.radioButton_7.setText(_translate("TeacherMainWindow", "False"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_9), _translate("TeacherMainWindow", "True Or False"))
        self.pushButton.setText(_translate("TeacherMainWindow", "Create Question"))
        self.label_2.setText(_translate("TeacherMainWindow", "Please Select The Correct Answers Before Clicking On Create Question Button"))
        self.radioButton_2.setText(_translate("TeacherMainWindow", "Option B"))
        self.radioButton_3.setText(_translate("TeacherMainWindow", "Option D"))
        self.textEdit_4.setHtml(_translate("TeacherMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_4.setText(_translate("TeacherMainWindow", "Option E"))
        self.radioButton_5.setText(_translate("TeacherMainWindow", "Option C"))
        self.pushButton_5.setText(_translate("TeacherMainWindow", "Preview Question Before Creating"))
        self.radioButton.setText(_translate("TeacherMainWindow", "Option A "))
        self.label.setText(_translate("TeacherMainWindow", "Question Body"))
        self.label_3.setText(_translate("TeacherMainWindow", "What is the Year Level Of The Question?"))
        self.label_5.setText(_translate("TeacherMainWindow", "What is the Question Phrase Tag?"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_10), _translate("TeacherMainWindow", "Five Options"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("TeacherMainWindow", "Multiple Choice"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_19), _translate("TeacherMainWindow", "ReOrder Code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TeacherMainWindow", "Create Question"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_11), _translate("TeacherMainWindow", "The Bank"))
        self.pushButton_2.setText(_translate("TeacherMainWindow", "Search By Year Level"))
        self.pushButton_3.setText(_translate("TeacherMainWindow", "Search By Phrase"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_12), _translate("TeacherMainWindow", "Search The Bank By Tag"))
        self.pushButton_8.setText(_translate("TeacherMainWindow", "View Question By ID"))
        self.pushButton_9.setText(_translate("TeacherMainWindow", "Modify Question By ID"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_13), _translate("TeacherMainWindow", "View Or Modify Question"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TeacherMainWindow", "Questions Bank"))
        self.label_13.setText(_translate("TeacherMainWindow", "Number Of Questions In Exam: "))
        self.label_14.setText(_translate("TeacherMainWindow", "(Maximum 10)"))
        self.label_15.setText(_translate("TeacherMainWindow", "Number Of School Classes In Exam: "))
        self.label_16.setText(_translate("TeacherMainWindow", "(Maximum 10)"))
        self.pushButton_10.setText(_translate("TeacherMainWindow", "Add Question To Exam By Question ID"))
        self.pushButton_12.setText(_translate("TeacherMainWindow", "Remove Question From Exam By Question ID"))
        self.pushButton_11.setText(_translate("TeacherMainWindow", "Add School Class To Exam By School Class ID"))
        self.pushButton_13.setText(_translate("TeacherMainWindow", "Remove School Class From Exam By School Class ID"))
        self.pushButton_14.setText(_translate("TeacherMainWindow", "Create Exam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("TeacherMainWindow", "Create Exam"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_15), _translate("TeacherMainWindow", "All Exams"))
        self.pushButton_15.setText(_translate("TeacherMainWindow", "View Exam Details By Exam ID"))
        self.label_19.setText(_translate("TeacherMainWindow", "Number Of Questions In Exam: "))
        self.label_21.setText(_translate("TeacherMainWindow", "Number Of School Classes In Exam: "))
        self.label_18.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_16), _translate("TeacherMainWindow", "View Exam Details"))
        self.label_22.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_23.setText(_translate("TeacherMainWindow", "Number Of School Classes In Exam: "))
        self.label_25.setText(_translate("TeacherMainWindow", "Number Of Questions In Exam: "))
        self.pushButton_17.setText(_translate("TeacherMainWindow", "Add Question To Exam By Question ID"))
        self.pushButton_18.setText(_translate("TeacherMainWindow", "Remove Question From Exam By Question ID"))
        self.pushButton_19.setText(_translate("TeacherMainWindow", "Add School Class To Exam By School Class ID"))
        self.pushButton_20.setText(_translate("TeacherMainWindow", "Remove School Class From Exam By School Class ID"))
        self.pushButton_21.setText(_translate("TeacherMainWindow", "Modify Exam"))
        self.label_27.setText(_translate("TeacherMainWindow", "(Maximum 10)"))
        self.label_28.setText(_translate("TeacherMainWindow", "(Maximum 10)"))
        self.pushButton_16.setText(_translate("TeacherMainWindow", "Modify Exam Details By Exam ID"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_17), _translate("TeacherMainWindow", "Modify Exam Details"))
        self.pushButton_22.setText(_translate("TeacherMainWindow", "De-Activate Exam By Exam ID"))
        self.pushButton_23.setText(_translate("TeacherMainWindow", "Re-Activate Exam By Exam ID"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_18), _translate("TeacherMainWindow", "Exam Activation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("TeacherMainWindow", "Exams Bank"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_22), _translate("TeacherMainWindow", "All Exam Results"))
        self.pushButton_24.setText(_translate("TeacherMainWindow", "Load Exam Results Details By Exam ID"))
        self.label_31.setText(_translate("TeacherMainWindow", "School Classes In The Exam"))
        self.label_33.setText(_translate("TeacherMainWindow", "Exam Result ID: "))
        self.pushButton_26.setText(_translate("TeacherMainWindow", "View Student Exam Result By Student ID"))
        self.pushButton_25.setText(_translate("TeacherMainWindow", "View School Class Details By School Class ID"))
        self.label_34.setText(_translate("TeacherMainWindow", "Student ID: "))
        self.label_35.setText(_translate("TeacherMainWindow", "Student Full Name: "))
        self.label_39.setText(_translate("TeacherMainWindow", "Date Of Birth: "))
        self.label_38.setText(_translate("TeacherMainWindow", "School Class ID: "))
        self.label_36.setText(_translate("TeacherMainWindow", "Exam ID: "))
        self.label_37.setText(_translate("TeacherMainWindow", "Overall Average Mark For This Exam:  "))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_23), _translate("TeacherMainWindow", "View Exam Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_21), _translate("TeacherMainWindow", "Exam Results Bank"))
        self.pushButton_4.setText(_translate("TeacherMainWindow", "Close"))
        self.pushButton_27.setText(_translate("TeacherMainWindow", "Log Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_20), _translate("TeacherMainWindow", "Close Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeacherMainWindow = QtWidgets.QMainWindow()
    ui = Ui_TeacherMainWindow()
    ui.setupUi(TeacherMainWindow)
    TeacherMainWindow.show()
    sys.exit(app.exec_())

